services:
  asterixdb:
    image: mp4sini/asterixdb:latest
    hostname: asterixdb
    container_name: asterixdb
    command:
      - /bin/bash
      - -c
      - |
        cp /asterixsetup/cc.conf opt/local/conf/cc.conf
        opt/local/bin/start-sample-cluster.sh
        tail -f /dev/null
    volumes:
      - "./asterixdbconf:/asterixsetup/"
    ports:
      - 19006:19006
      - 19002:19002
      - 19001:19001
      - 19003:19003
      - 1009:1009
      - 1098:1098

  dtgraph:
    image: mp4sini/dtgraph
    hostname: dtgraph
    container_name: dtgraph
    volumes:
      - "./results:/dt_graph/results"
      - "./logs:/dt_graph/logs"
    env_file: .env
    depends_on:
      - asterixdb
    command:
      - /bin/bash
      - -c
      - |
        ./wait-for-it.sh asterixdb:19006 -t 90 -- echo "AsterixDB running, starting to ingest data..."
        chmod +x scripts/download_dataset.sh
        chmod +x scripts/run_smartbench_evaluation.sh
        ./scripts/run_smartbench_evaluation.sh
