version: "3.9"
services:
  asterixdb:
    image: mp4sini/asterixdb:latest
    hostname: asterixdb
    container_name: asterixdb
    command:
      - /bin/bash
      - -c
      - |
        opt/local/bin/start-sample-cluster.sh
        curl -X POST "http://localhost:19002/query/service" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "statement=$(cat /asterixsetup/setup.txt)" \
        --data-urlencode "pretty=true" \
        --data-urlencode "mode=immediate" \

        tail -f /dev/null
    volumes:
      - "./asterixdbconf:/asterixsetup/"
    ports:
      - 19006:19006
      - 19002:19002
      - 19001:19001
      - 19003:19003
      - 1009:1009
      - 1098:1098
      - 10001-10600:10001-10600

