version: "3.9"
services:
  asterix_cc:
    image: mp4sini/asterixdb:latest
    ports:
      - 19006:19006
      - 19001:19001
      - 19002:19002
      - 19003:19003
      - 1009:1009
      - 1098:1098

    volumes:
      - asterix_conf:/workspace/asterixdb/asterixdb/asterix-server/target/asterix-server-0.9.10-SNAPSHOT-binary-assembly/apache-asterixdb-0.9.10-SNAPSHOT/opt/local/conf
      - datasource_jar:/asterixsetup/
    command:
      - /bin/bash
      - -c
      - |
        sleep 20
        bin/asterixcc -config-file opt/local/conf/cc.conf > cc.log 2>&1 &
        sleep 10
        curl -X POST "http://localhost:19002/query/service" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "statement=$$(cat /asterixsetup/setup.txt)" \
        --data-urlencode "pretty=true" \
        --data-urlencode "mode=immediate"
        tail -f /dev/null
    deploy:
      placement:
        constraints:
          - node.hostname == ISI-BIGCLUSTER-PNRR06
    networks:
      - BIG-dataplatform-network

  asterix_nc1:
    image: mp4sini/asterixdb:latest
    ports:
      - 1099:1099
      - 9090:9090
#    volumes:
#      - asterix_conf:/workspace/asterixdb/asterixdb/asterix-server/target/asterix-server-0.9.10-SNAPSHOT-binary-assembly/apache-asterixdb-0.9.10-SNAPSHOT/opt/local/conf
    command:
      - /bin/bash
      - -c
      - |
        bin/asterixncservice > asterix_nc1.log 2>&1 &
        tail -f /dev/null
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network

  asterix_nc2:
    image: mp4sini/asterixdb:latest
    ports:
      - 1099:1099
      - 9090:9090
#    volumes:
#      - asterix_conf:/workspace/asterixdb/asterixdb/asterix-server/target/asterix-server-0.9.10-SNAPSHOT-binary-assembly/apache-asterixdb-0.9.10-SNAPSHOT/opt/local/conf
    command:
      - /bin/bash
      - -c
      - |
        bin/asterixncservice > asterix_nc1.log 2>&1 &
        tail -f /dev/null
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1
    networks:
      - BIG-dataplatform-network

#  dataSources:
#    image: openjdk:21-jdk
#    volumes:
#      - asterix_test_results:/asterix_statistics/
#      - datasource_jar:/asterix/
#    command: ["/asterix/startup.sh"]
#    deploy:
#      restart_policy:
#        condition: none
#      replicas: 1
#      placement:
#        constraints:
#          - node.hostname != CB-Mass-Node1
#          - node.hostname != ISI-BIGCLUSTER-PNRR06
#    networks:
#      - asterix-network
#    environment:
#      INGESTION_LATENCY: 0
#      ASTERIX_IP: asterixdb
#      MAX_ITERATION: 5000
#      TEST_ID: 0
#      ASTERIX_MACHINES_COUNT: 1
#      DATASOURCES_NUMBER: 4

volumes:
  asterix_conf:
    driver_opts:
      type: nfs
      o: addr=192.168.30.249,rw,nfsvers=4,nolock,hard
      device: ":/nfsshare/asterixdb/conf/cc_conf/"

  datasource_jar:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.30.249,rw,nfsvers=4,nolock,hard
      device: ":/nfsshare/asterixdb/jar/"

networks:
  BIG-dataplatform-network:
    external: true
    name: BIG-dataplatform-network
