version: "3.9"

x-datasource-common:
  &datasource-common
  image: openjdk:21-jdk
  environment:
    INGESTION_LATENCY: 0
    ASTERIX_IP: asterixdb
    ASTERIX_PORT: 10001
    MAX_ITERATION: 50000
    TEST_ID: 0
    ASTERIX_MACHINES_COUNT: 1
    DATASOURCES_NUMBER: 4
  volumes:
    - asterix_test_results:/asterix_statistics/
    - datasource_jar:/asterix/
  command:
    - /bin/bash
    - -c
    - |
      java -jar /asterix/STS-Graph-all.jar
  deploy:
    placement:
      constraints:
        - node.hostname != CB-Mass-Node1
  networks:
    - asterix-network

services:
#  dataSource_1:
#    <<: *datasource-common
#    environment:
#      TS_ID: 1
#  dataSource_2:
#    <<: *datasource-common
#    environment:
#      TS_ID: 2
#  dataSource_3:
#    <<: *datasource-common
#    environment:
#      TS_ID: 3
#  dataSource_4:
#    <<: *datasource-common
#    environment:
#      TS_ID: 4

  asterixdb:
    image: mp4sini/asterixdb:latest
    volumes:
      - datasource_jar:/asterixsetup/
    ports:
      - 49006:19006
      - 19002:19002
      - 10001:10001
    networks:
      - asterix-network
    command:
      - /bin/bash
      - -c
      - |
        opt/local/bin/start-sample-cluster.sh
        curl -X POST "http://localhost:19002/query/service" \
        -H "Content-Type: application/x-www-form-urlencoded" \
        --data-urlencode "statement=$(cat /asterixsetup/setup.txt)" \
        --data-urlencode "pretty=true" \
        --data-urlencode "mode=immediate" \
        tail -f /dev/null
    deploy:
      placement:
        constraints:
          - node.hostname != CB-Mass-Node1

volumes:
  asterix_test_results:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.30.249,rw,nfsvers=4,nolock,hard
      device: ":/nfsshare/asterixdb/results/"

  datasource_jar:
    driver: local
    driver_opts:
      type: nfs
      o: addr=192.168.30.249,rw,nfsvers=4,nolock,hard
      device: ":/nfsshare/asterixdb/jar/"


networks:
  asterix-network:
    external: true
